import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Header from "./components/header/Header";
// import { ThemeContext } from "./context/context";



config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-Poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${poppins.variable} antialiased h-full`}>
        {/* <ThemeContext.Provider value={{ user: "John Doe" }}> */}
          <Header />
          <main className="w-full h-[calc(100vh-96px)]">
            {children}
          </main>
        {/* </ThemeContext.Provider> */}
      </body>
    </html>
  );
}
